apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sync-waves
spec:
  project: default
  source:
    repoURL: https://github.com/colinjlacy/argocd-sync-waves-lightning-talk
    path: chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
